Add navigation files
suguruhamada1003910/swd_ros2_starter_kit_bringup pull request #1
Opened 2023-04-19 06:23 UTC by tk-ono

SLAMとNavigationのlaunchファイルとパラメータ設定ファイルを作成しました。

2023-04-19 07:58 UTC, suguruhamada1003910 reviewed
swd_ros2_controllerのNode立ち上げの記述が長すぎてlaunchファイルを読みづらいため、launchファイルを分離してもらえませんか？

2023-04-20 04:39 UTC, tk-ono commented
controllerのlaunchfileを分離しました。

2023-04-20 04:53 UTC, suguruhamada1003910 requested changes
コメントチェックお願いします。

2023-04-20 04:53 UTC, suguruhamada1003910 commented on launch/navigation.launch.py
> +    session = "/tmp/SYSTEMCTL_dbus.id"
swd_controllersノードでのみ必要な記述なので、このファイルには不要では？

2023-04-20 04:53 UTC, suguruhamada1003910 commented on launch/mapping.launch.py
> +        print("SYSTEMCTL_dbus.id detected")
swd_controllersノードでのみ必要な記述なので、このファイルには不要では？

2023-04-20 04:53 UTC, suguruhamada1003910 commented on params/starter_kit_navigation_params.yaml
> +      # Add high threshold velocity for turtlebot 3 issue.
途中でTurtlebotの記述が入っているのですが、これは意図的でしょうか？

2023-04-20 04:53 UTC, suguruhamada1003910 commented on params/starter_kit_navigation_params.yaml
> +      # Add high threshold velocity for turtlebot 3 issue.
不要なコメントでは？という指摘です。

2023-04-20 05:20 UTC, suguruhamada1003910 commented on launch/mapping.launch.py
> +            'use_sim_time',
use_sim_timeの定義が２回目なので、1回でいいのでは？
また、launch時の変数として定義していますが、trueとfalseで使い分けるのはどういうときでしょうか？（常にfalseであれば、定義する意味があまりないかと）

2023-04-20 05:20 UTC, tk-ono commented on launch/navigation.launch.py
> +    session = "/tmp/SYSTEMCTL_dbus.id"
ご指摘どおり不要でした。該当箇所を削除しました。

2023-04-20 05:20 UTC, tk-ono commented on launch/mapping.launch.py
> +        print("SYSTEMCTL_dbus.id detected")
ご指摘どおり不要でした。該当箇所を削除しました。

2023-04-20 05:20 UTC, suguruhamada1003910 commented on launch/navigation.launch.py
> +            'use_sim_time',
use_sim_timeの定義が２回目なので、1回でいいのでは？
また、launch時の変数として定義していますが、trueとfalseで使い分けるのはどういうときでしょうか？（常にfalseであれば、定義する意味があまりないかと）

2023-04-20 05:20 UTC, tk-ono commented on params/starter_kit_navigation_params.yaml
> +      # Add high threshold velocity for turtlebot 3 issue.
意図としましては公式のyaml fileに記述がありましたので、そのまま記述しておりましたが、
確認するとTurtlebotに関するissueなのでコメントを削除しました
https://github.com/ros-planning/navigation2/blob/9307dbc0183268117ddbe36833950088b275719d/nav2_bringup/params/nav2_params.yaml#L151

2023-04-20 05:22 UTC, suguruhamada1003910 requested changes
use_sim_timeについて指摘しました。

2023-04-20 05:29 UTC, tk-ono commented on launch/mapping.launch.py
> +            'use_sim_time',
不要でした。
use_sim_timeはsimulation(rosbagやgazebo)で動かすときにtrueにする必要がありますので、変数としています。

2023-04-20 05:29 UTC, tk-ono commented on launch/navigation.launch.py
> +            'use_sim_time',
不要でした。該当箇所を削除しました。
use_sim_timeはsimulation(rosbagやgazebo)で動かすときにtrueにする必要がありますので、変数としています。

2023-04-20 05:31 UTC, tk-ono commented
use_sim_timeの記述を修正いたしました。ご確認お願いいたします。

2023-04-20 05:45 UTC, suguruhamada1003910 commented on launch/mapping.launch.py
> +    use_sim_time = LaunchConfiguration('use_sim_time', default = 'false')
一応確認ですが、将来のgazeboでの挙動を見越して、use_sim_timeパラメーターを残しているということでいいでしょうか？
[swd_controller.launch.py](https://github.com/suguruhamada1003910/swd_ros2_starter_kit_bringup/pull/1/files#diff-154bc7a8dea4e89c1c0388a0b83ee39741afd98b9fed34e9890e9bb62677b3b8)
では、与えられるパラメーターとして、
use_sim_time = LaunchConfiguration('use_sim_time', default = 'false')
baseline_m = LaunchConfiguration('baseline_m', default = '0.485')
pub_freq_hz = LaunchConfiguration('pub_freq_hz', default = '50')
base_frame = LaunchConfiguration('base_frame', default = 'base_footprint')
odom_frame = LaunchConfiguration('odom', default = 'odom')
motor_max_speed_rpm = LaunchConfiguration('motor_max_speed_rpm', default = '1050')
を定義しています。
上位になるlaunchファイルで、use_sim_timeのみ設定できるようにする意図について確認させてください。

2023-04-20 06:01 UTC, tk-ono commented on launch/mapping.launch.py
> +    use_sim_time = LaunchConfiguration('use_sim_time', default = 'false')
はい。
use_sim_timeはSWD Starter Kitの構成をかえずともgazeboなどのシミュレーションで使用する場合は頻繁に変えるので上位で明記しています。
その他のパラメータはメカ・ハードなどの構成が変わったときは変更が必要なので、パラメータ化（必要に応じて追記できるように）していますが上位で明記はしておりません。

2023-04-21 00:27 UTC, suguruhamada1003910 requested changes
LaunchConfigurationの必要性について確認してください。

2023-04-21 00:27 UTC, suguruhamada1003910 commented on launch/swd_controller.launch.py
> +    use_sim_time = LaunchConfiguration('use_sim_time', default = 'false')
もう一度考えましたが、やはり上位のlaunchファイルにLaunchConfigurationしないのであれば、ここで定義してもユーザー側にはメリットがないのかなと思います。削除するか、上位にも記載してはどうでしょうか？

2023-04-21 04:23 UTC, suguruhamada1003910 approved these changes
問題ありません。

2023-04-21 04:42 UTC, tk-ono commented
別途ご指摘のありましたカッコの位置を修正しました。

2023-04-21 04:43 UTC, merged